### ISSUE TITLE
Stuck at loading data for streamers

### ISSUE THREAD

**Issue by bitteL3BN** [twesterapp/twester#48]
"
21.5.2022 10:24:23 - Watcher is booting...

21.5.2022 10:24:23 - Loading data for 8 streamers...
"

doesn't work anymore :(
can't even press the pause button

**Comment by ceoshikhar** [comment]
Does closing and reopening the program fix it or is it stuck? I am saying this because it's working fine for me. Could be that some memory leak happened and it froze. 

Also, if it's getting stuck there ever after rebooting then can you please open up the developer console by pressing F12 or Control/Command + Shift + n and then go to `console` tab and copy all the logs and paste them here.

**Comment by bitteL3BN** [comment]
omg the logs helped me to solve this problem. i still had xqc under xqcow in my streamerlist and that made the program fail to load properly couse he renaimed his channel. thanks for the quick response. everything is working fine again.

**Comment by ceoshikhar** [comment]
Glad to help. 

_BTW, I am some sort of a juicer myself._
